### ISSUE TITLE
Side orders (such as yogurt and beverages) require a primary food item to be ordered from the same supplier

### ISSUE THREAD

**Issue by daway0** [daway0/pors#203]
Based on the discussion in the meeting:

If a side order (non-primary food item) is ordered, the main food item must also be from the same supplier. 

For example, if the main food item is from restaurant X, only side items from restaurant X can be selected. In the future, if a staff member can order multiple primary food items from suppliers X and Y, they should be able to select side items from both X and Y.

**Subtasks to be implemented:**

1. **Settings Implementation**: Add a field to settings to on and off this feature.
2. **Backend**: Implement necessary changes in the backend.
3. **Frontend**: Develop a new menu where:
   - Clicking on the lunch menu shows two sub-menus: Main Food and Side Orders.
   - Once a main food item is selected, the side menu should unlock and draw attention for selection.
   - Side items should be displayed and selectable based on the supplier of the main food item.
   
Another UI implementation idea was to include a side menu alongside the breakfast and lunch menus. However, this approach was problematic because if a dinner menu was added, another menu for dinner sides would be needed, resulting in up to 5 menus for a regular day.

Instead, as seen in the image, various menus for different meal times (like lunch) could be incorporated within the same lunch menu.
![image](https://github.com/user-attachments/assets/6bf71915-a7dc-466d-b31c-620c0e2687cc)

@ArCaneSec sub tasks
   - [ ] #213
   - [ ] #214
- [ ] #215

**Comment by daway0** [comment]
@ArCaneSec sub tasks
**Restrict Drink and Side Orders to Main Dish Providers**:
   - [ ] Ensure that drinks and side dishes can only be ordered from the same providers from whom the main dishes have been ordered.
   - [ ] This restriction should be configurable as a toggle variable in the settings.

**Server-Side Calculation After Main Dish Selection**:
Since all calculations have been handled server-side so far, it's recommended to continue this approach.
- [ ] After the main dish is selected, a request is sent to the server to calculate which side dishes the user is allowed to order based on the main dishes they have chosen.
- [ ] Once the calculation is complete, unlock the side dish menu to allow selection.

**Clear Side Dishes if Main Dish is Removed**:
- [ ] If a main dish is removed from the order, ensure that any associated side dishes are also removed 
- [ ] Additionally, side dishes should no longer be displayed in the daily lunch menu.

**Comment by daway0** [comment]
@ArCaneSec 

Can you give me more detail about admin behavior on this? 
Can they bypass the restrictions?!

**Comment by daway0** [comment]
@ArCaneSec 

When an order contains one main dish and several sides, deleting one side results in the deletion of all the other sides as well

**Comment by ArCaneSec** [comment]
after discussion on discord, we decided to not let admins bypass this restriction, unless they explicitly ask for it.

**Comment by daway0** [comment]
> @ArCaneSec
> 
> Can you give me more detail about admin behavior on this? Can they bypass the restrictions?!

after discussion on discord, we decided to not let admins bypass this restriction, unless they explicitly ask for it.
